name: GitGuardian Scan

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  ggshield:
    name: GitGuardian Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run GitGuardian ggshield scan
        uses: GitGuardian/ggshield-action@v1
        with:
          args: scan path --exit-zero .
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
